import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import Banner from "@/components/Banner";
import { Menu } from "@/components/Menu";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <h1>Hola mundi</h1> */}
      <body className={nunito.className}>
        <Banner />
        <Navbar />
        <Menu />
        <main className="max-w-10xl mx-auto">{children}</main>
      </body>
    </html>
  );
}
